name: Daily News Processing and Delivery

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'
    - cron: '30 19 * * *'

jobs:
  process-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebase-service-account.json

      - name: Create .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> .env
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env
          echo "SMTP_SERVER=mail.smtp2go.com" >> .env
          echo "SMTP_PORT=2525" >> .env
          echo "EMAIL_FROM=${{ secrets.EMAIL_FROM }}" >> .env
          echo "EMAIL_RECIPIENTS=${{ secrets.EMAIL_RECIPIENTS }}" >> .env
          echo "GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account.json" >> .env

      - name: Run get_today_news.py
        if: github.event.schedule == '0 19 * * *' || github.event_name == 'workflow_dispatch'
        run: python get_today_news.py

      - name: Run news_delivery.py
        if: github.event.schedule == '30 19 * * *' || github.event_name == 'workflow_dispatch'
        run: python news_delivery.py

      - name: Cleanup sensitive files
        if: always()
        run: |
          rm -f firebase-service-account.json
          rm -f .env 