name: News Delivery

on:
  schedule:
    # Run at 19:30 UTC+8 (11:30 UTC)
    - cron: '30 11 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  deliver-news:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> .env
        echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
        echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> .env
        echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env
        echo "EMAIL_FROM=${{ secrets.EMAIL_FROM }}" >> .env
        echo "EMAIL_RECIPIENTS=${{ secrets.EMAIL_RECIPIENTS }}" >> .env
    
    - name: Set up Firebase credentials
      run: |
        echo '${{ secrets.FIREBASE_CREDENTIALS }}' > firebase_credentials.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=firebase_credentials.json" >> .env
    
    - name: Run news delivery script
      run: python news_delivery.py
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: delivery-logs
        path: delivery.log
    
    - name: Cleanup sensitive files
      if: always()
      run: |
        rm -f .env
        rm -f firebase_credentials.json 