name: News Delivery

on:
  schedule:
    # Run news_delivery.py at 19:30 UTC+8 (11:30 UTC)
    - cron: '30 11 * * *'
  workflow_dispatch:

jobs:
  process-news:
    name: Deliver News Articles
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        cat << EOF > .env
        SMTP_SERVER=${{ secrets.SMTP_SERVER }}
        SMTP_PORT=${{ secrets.SMTP_PORT }}
        SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
        EMAIL_FROM=${{ secrets.EMAIL_FROM }}
        EMAIL_RECIPIENTS=${{ secrets.EMAIL_RECIPIENTS }}
        OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        EOF
    
    - name: Run news delivery
      run: python news_delivery.py
    
    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: news-delivery-logs
        path: delivery.log
    
    - name: Cleanup sensitive files
      run: |
        rm -f .env
        rm -f delivery.log 