name: SEA News Collection

on:
  schedule:
    # Run get_today_news.py at 21:35 uae
    - cron: '38 5 * * *'
  workflow_dispatch:

jobs:
  collect-news:
    name: Collect News Articles
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Setup Firebase credentials
      run: |
        echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > firebase-service-account.json
        # Verify JSON is valid
        python -c "import json; json.load(open('firebase-service-account.json'))"
        echo "GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account.json" >> $GITHUB_ENV
    
    - name: Create .env file
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
        echo "GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account.json" >> .env
    
    - name: Run get_today_news.py
      run: python get_today_news.py
    
    - name: List files for debugging
      run: ls -R
      
    - name: Upload collection logs
      uses: actions/upload-artifact@v4
      with:
        name: news-collection-logs
        path: |
          *.log
          logs/
    
    - name: Cleanup sensitive files
      if: always()
      run: |
        rm -f firebase-service-account.json
        rm -f .env 
