name: SEA News Delivery

on:
  schedule:
    # Run news_delivery.py at 19:30 UTC+8 (11:30 UTC)
    - cron: '30 11 * * *'
  workflow_dispatch:

jobs:
  deliver-news:
    name: Deliver News Articles
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> .env
        echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env
        echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> .env
        echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
        echo "EMAIL_FROM=${{ secrets.EMAIL_FROM }}" >> .env
        echo "EMAIL_RECIPIENTS=${{ secrets.EMAIL_RECIPIENTS }}" >> .env
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
    
    - name: Run news_delivery.py
      run: |
        # Print environment for debugging (excluding sensitive values)
        env | grep -v "KEY\|PASSWORD" || true
        
        # Run the script
        python news_delivery.py
    
    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: news-delivery-logs
        path: |
          *.log
          logs/
    
    - name: Cleanup sensitive files
      if: always()
      run: |
        rm -f .env 